TOP = ..

EBIN = \
       posix_errno.beam \
       posix_misc.beam \
       idpool.beam \
       fuse_kernel.beam \
       fuse_kernel_handler.beam \
       fuse_lowlevel_test.beam

include $(TOP)/include.mk

